
package Telaprincipal;

/**
 *
 * @author johnp
 */
public class Ajuda extends javax.swing.JFrame {

    /**
     * Creates new form Ajuda
     */
    public Ajuda() {
        initComponents();
    jTextField1.setEditable(false);
    textArea1.setEditable(false);
    setLocationRelativeTo(null);
    setResizable(false);
    


    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        Errocombcd = new javax.swing.JTabbedPane();
        jPanel10 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jPanel14 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jPanel15 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jPanel16 = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        jLabel46 = new javax.swing.JLabel();
        jPanel11 = new javax.swing.JPanel();
        textArea2 = new java.awt.TextArea();
        jLabel47 = new javax.swing.JLabel();
        jLabel48 = new javax.swing.JLabel();
        jPanel13 = new javax.swing.JPanel();
        jLabel49 = new javax.swing.JLabel();
        jLabel50 = new javax.swing.JLabel();
        jLabel51 = new javax.swing.JLabel();
        jPanel12 = new javax.swing.JPanel();
        jTextField1 = new javax.swing.JTextField();
        jLabel52 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel40 = new javax.swing.JLabel();
        jLabel41 = new javax.swing.JLabel();
        jLabel42 = new javax.swing.JLabel();
        jLabel43 = new javax.swing.JLabel();
        jLabel44 = new javax.swing.JLabel();
        textArea1 = new java.awt.TextArea();
        jLabel45 = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(650, 650));
        getContentPane().setLayout(null);

        Errocombcd.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        Errocombcd.setMinimumSize(new java.awt.Dimension(600, 700));
        Errocombcd.setPreferredSize(getMinimumSize());

        jPanel10.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel1.setText("basta entrar em contato conosco através do SAC!");
        jPanel10.add(jLabel1);
        jLabel1.setBounds(20, 520, 560, 14);

        jLabel2.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel2.setText("* Posso executar a aplicação em diferentes sistemas operacionais?");
        jPanel10.add(jLabel2);
        jLabel2.setBounds(10, 100, 380, 14);

        jLabel3.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel3.setText("A resposta é , sim! contato que entre em contato conosco para exportamos seu banco de dados");
        jPanel10.add(jLabel3);
        jLabel3.setBounds(20, 120, 550, 14);

        jLabel4.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel4.setText("evirtando sofrer perdas de informações presentes na aplicação. Para mais informações, entre em ");
        jPanel10.add(jLabel4);
        jLabel4.setBounds(20, 140, 550, 14);

        jLabel5.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel5.setText("contato conosco pela aréa do SAC.");
        jPanel10.add(jLabel5);
        jLabel5.setBounds(20, 160, 550, 14);

        jLabel6.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel6.setText("*Como faço para atualizar a aplicação para a versão mais recente?");
        jPanel10.add(jLabel6);
        jLabel6.setBounds(10, 200, 550, 14);

        jPanel14.setLayout(null);

        jLabel7.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel7.setText("Enttraremos em contato quando uma versão mais recente do nosso software estiver disponível!");
        jPanel14.add(jLabel7);
        jLabel7.setBounds(10, 170, 550, 14);

        jLabel8.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel8.setText("* Posso executar a aplicação em diferentes sistemas operacionais?");
        jPanel14.add(jLabel8);
        jLabel8.setBounds(10, 50, 380, 14);

        jLabel9.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel9.setText("A resposta é , sim! contato que entre em contato conosco para exportamos seu banco de dados");
        jPanel14.add(jLabel9);
        jLabel9.setBounds(10, 70, 550, 14);

        jLabel10.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel10.setText("e não sofrer perdas de informações presentes na aplicação, para mais informações, entre em ");
        jPanel14.add(jLabel10);
        jLabel10.setBounds(10, 90, 550, 14);

        jLabel11.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel11.setText("contato conosco pela aréa do SAC.");
        jPanel14.add(jLabel11);
        jLabel11.setBounds(10, 110, 550, 14);

        jLabel12.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel12.setText("*Como faço para atualizar a aplicação para a versão mais recente?");
        jPanel14.add(jLabel12);
        jLabel12.setBounds(10, 150, 550, 14);

        jPanel10.add(jPanel14);
        jPanel14.setBounds(0, 0, 0, 0);

        jPanel15.setLayout(null);

        jLabel13.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel13.setText("Enttraremos em contato quando uma versão mais recente do nosso software estiver disponível!");
        jPanel15.add(jLabel13);
        jLabel13.setBounds(10, 170, 550, 14);

        jLabel14.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel14.setText("* Posso executar a aplicação em diferentes sistemas operacionais?");
        jPanel15.add(jLabel14);
        jLabel14.setBounds(10, 50, 380, 14);

        jLabel15.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel15.setText("A resposta é , sim! contato que entre em contato conosco para exportamos seu banco de dados");
        jPanel15.add(jLabel15);
        jLabel15.setBounds(10, 70, 550, 14);

        jLabel16.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel16.setText("e não sofrer perdas de informações presentes na aplicação, para mais informações, entre em ");
        jPanel15.add(jLabel16);
        jLabel16.setBounds(10, 90, 550, 14);

        jLabel17.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel17.setText("contato conosco pela aréa do SAC.");
        jPanel15.add(jLabel17);
        jLabel17.setBounds(10, 110, 550, 14);

        jLabel18.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel18.setText("*Como faço para atualizar a aplicação para a versão mais recente?");
        jPanel15.add(jLabel18);
        jLabel18.setBounds(10, 150, 550, 14);

        jPanel16.setLayout(null);

        jLabel19.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel19.setText("Enttraremos em contato quando uma versão mais recente do nosso software estiver disponível!");
        jPanel16.add(jLabel19);
        jLabel19.setBounds(10, 170, 550, 14);

        jLabel20.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel20.setText("* Posso executar a aplicação em diferentes sistemas operacionais?");
        jPanel16.add(jLabel20);
        jLabel20.setBounds(10, 50, 380, 14);

        jLabel21.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel21.setText("A resposta é , sim! contato que entre em contato conosco para exportamos seu banco de dados");
        jPanel16.add(jLabel21);
        jLabel21.setBounds(10, 70, 550, 14);

        jLabel22.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel22.setText("e não sofrer perdas de informações presentes na aplicação, para mais informações, entre em ");
        jPanel16.add(jLabel22);
        jLabel22.setBounds(10, 90, 550, 14);

        jLabel23.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel23.setText("contato conosco pela aréa do SAC.");
        jPanel16.add(jLabel23);
        jLabel23.setBounds(10, 110, 550, 14);

        jLabel24.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel24.setText("*Como faço para atualizar a aplicação para a versão mais recente?");
        jPanel16.add(jLabel24);
        jLabel24.setBounds(10, 150, 550, 14);

        jPanel15.add(jPanel16);
        jPanel16.setBounds(0, 0, 0, 0);

        jPanel10.add(jPanel15);
        jPanel15.setBounds(0, 0, 0, 0);

        jLabel25.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel25.setText("Entraremos em contato quando uma versão mais recente do nosso software estiver disponível!");
        jPanel10.add(jLabel25);
        jLabel25.setBounds(10, 220, 550, 14);

        jLabel26.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel26.setText("*A aplicação possui suporte para vários idiomas?");
        jPanel10.add(jLabel26);
        jLabel26.setBounds(10, 260, 550, 14);

        jLabel27.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel27.setText("*A aplicação possui suporte para vários idiomas?");
        jPanel10.add(jLabel27);
        jLabel27.setBounds(10, 260, 550, 14);

        jLabel28.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel28.setText("No momento a aplicação não conta com suporte em outros idiomas. Tal suporte será implementado");
        jPanel10.add(jLabel28);
        jLabel28.setBounds(20, 280, 560, 14);

        jLabel29.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel29.setText("em atualizações futuras!");
        jPanel10.add(jLabel29);
        jLabel29.setBounds(20, 310, 560, 14);

        jLabel30.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel30.setText("*");
        jPanel10.add(jLabel30);
        jLabel30.setBounds(0, 320, 560, 14);

        jLabel31.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel31.setText("*Como faço para relatar um problema ou enviar um feedback sobre a aplicação?");
        jPanel10.add(jLabel31);
        jLabel31.setBounds(10, 340, 560, 14);

        jLabel32.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel32.setText("Ficamos contentes em sua preocupação em relatar algum problema ou compartilhar um feedback");
        jPanel10.add(jLabel32);
        jLabel32.setBounds(20, 360, 560, 14);

        jLabel33.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel33.setText("sobre o uso da apliação, no momento você pode acessar o link na aba do \"Quem somos?\", onde");
        jPanel10.add(jLabel33);
        jLabel33.setBounds(20, 380, 560, 14);

        jLabel34.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel34.setText("você encontrara informações pertinentes e paginas para prestar seu feedback, além disso você");
        jPanel10.add(jLabel34);
        jLabel34.setBounds(20, 400, 560, 14);

        jLabel35.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel35.setText("pode falar com nossa central, pela aba do SAC!");
        jPanel10.add(jLabel35);
        jLabel35.setBounds(20, 420, 560, 14);

        jLabel36.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel36.setText("*A aplicação possui alguma opção de backup automático dos dados?");
        jPanel10.add(jLabel36);
        jLabel36.setBounds(10, 460, 560, 14);

        jLabel37.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel37.setText("A aplicação possui sim um bakup automático dos dados armazenados na própria máquina, mas");
        jPanel10.add(jLabel37);
        jLabel37.setBounds(20, 480, 560, 14);

        jLabel38.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel38.setText("caso o proprietario da aplicação deseje fazer um upgrade para o salvamento autopmatico na nuvem");
        jPanel10.add(jLabel38);
        jLabel38.setBounds(20, 500, 560, 14);

        jLabel46.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/allgreenmtpequeno.png"))); // NOI18N
        jPanel10.add(jLabel46);
        jLabel46.setBounds(-660, 0, 1410, 1220);

        Errocombcd.addTab("Pergunas frequentes", jPanel10);

        jPanel11.setLayout(null);

        textArea2.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        textArea2.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        textArea2.setText("A verificação de login desempenha um papel crucial na proteção dos dados e na segurança dos sistemas e aplicativos online.\n Ao exigir que os usuários autentiquem sua identidade através de credenciais específicas, como nome de usuário e senha, a verificação de login\n impede o acesso não autorizado a informações sensíveis e recursos protegidos. Isso é essencial para garantir a privacidade dos usuários e\n prevenir potenciais violações de dados.  Além disso, a verificação de login permite um controle preciso sobre quem pode acessar o sistema e em que capacidade.\nPor meio da atribuição de diferentes níveis de permissões, os administradores podem garantir que apenas usuários autorizados tenham acesso a determinadas funcionalidades\n ou áreas do sistema. Isso não só protege os dados, mas também ajuda a evitar possíveis danos causados por atividades maliciosas ou inadvertidas.  \nPor fim, a verificação de login não apenas aumenta a segurança do sistema, mas também desempenha um papel importante na conformidade regulatória.\nEm muitos setores, existem leis e regulamentações que exigem a implementação de medidas de segurança, incluindo a verificação de login, para proteger a privacidade e a integridade dos dados dos usuários. \nPortanto, ao adotar práticas de verificação de login robustas, as organizações podem não apenas proteger seus sistemas e usuários, mas também evitar possíveis penalidades legais e manter a confiança do público");
        jPanel11.add(textArea2);
        textArea2.setBounds(21, 70, 570, 380);

        jLabel47.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jLabel47.setText("Por que é tao importante?");
        jPanel11.add(jLabel47);
        jLabel47.setBounds(150, 40, 280, 28);

        jLabel48.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/algreenpadra.png"))); // NOI18N
        jPanel11.add(jLabel48);
        jLabel48.setBounds(-750, -10, 1500, 1350);

        Errocombcd.addTab("Verificação login", jPanel11);

        jPanel13.setLayout(null);

        jLabel49.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel49.setText("atraves do nosso SAC! ficaremos honrados em responder suas duvidas...");
        jPanel13.add(jLabel49);
        jLabel49.setBounds(80, 140, 480, 30);

        jLabel50.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel50.setText("Caso obtenha algum erro do banco de dados, por favor, entre em contato");
        jPanel13.add(jLabel50);
        jLabel50.setBounds(80, 100, 500, 50);

        jLabel51.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/Bcdadosicon.png"))); // NOI18N
        jPanel13.add(jLabel51);
        jLabel51.setBounds(-430, -70, 1120, 690);

        Errocombcd.addTab("Erro com Banco de dados", jPanel13);

        jPanel12.setLayout(null);

        jTextField1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jTextField1.setForeground(new java.awt.Color(0, 51, 51));
        jTextField1.setText("https://www.instagram.com/allgreen1_?igsh=MWE2M3BqZWFidGxoNw==");
        jTextField1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 153, 0)));
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        jPanel12.add(jTextField1);
        jTextField1.setBounds(70, 370, 500, 50);

        jLabel52.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/algreenpadra.png"))); // NOI18N
        jPanel12.add(jLabel52);
        jLabel52.setBounds(-750, -10, 1500, 1250);

        Errocombcd.addTab("Quem somos?", jPanel12);

        jPanel1.setMinimumSize(new java.awt.Dimension(591, 650));
        jPanel1.setLayout(null);

        jLabel40.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel40.setText("Celular: ");
        jPanel1.add(jLabel40);
        jLabel40.setBounds(30, 120, 60, 20);

        jLabel41.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel41.setText("E-mail:");
        jPanel1.add(jLabel41);
        jLabel41.setBounds(30, 190, 60, 20);

        jLabel42.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel42.setText("Contatos");
        jPanel1.add(jLabel42);
        jLabel42.setBounds(30, 70, 180, 20);

        jLabel43.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel43.setText("johnpazzz01@gmail.com");
        jPanel1.add(jLabel43);
        jLabel43.setBounds(30, 220, 180, 20);

        jLabel44.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel44.setText("Linkedin:");
        jPanel1.add(jLabel44);
        jLabel44.setBounds(30, 270, 80, 20);

        textArea1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        textArea1.setText("https://www.linkedin.com/in/john-victor-0a4251289?utm_source=share&utm_campaign=share_via&utm_content=profile&utm_medium=android_app ");
        jPanel1.add(textArea1);
        textArea1.setBounds(30, 320, 480, 100);

        jLabel45.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel45.setText("+55 (083) 98692-8573");
        jPanel1.add(jLabel45);
        jLabel45.setBounds(30, 150, 180, 20);

        jLabel39.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/algreenpequeno.png"))); // NOI18N
        jPanel1.add(jLabel39);
        jLabel39.setBounds(-680, 0, 1310, 1270);

        Errocombcd.addTab("SAC", jPanel1);

        getContentPane().add(Errocombcd);
        Errocombcd.setBounds(0, 0, 630, 660);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
    }//GEN-LAST:event_jTextField1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ajuda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ajuda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ajuda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ajuda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ajuda().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTabbedPane Errocombcd;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel49;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel50;
    private javax.swing.JLabel jLabel51;
    private javax.swing.JLabel jLabel52;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField jTextField1;
    private java.awt.TextArea textArea1;
    private java.awt.TextArea textArea2;
    // End of variables declaration//GEN-END:variables
}
