package Telaprincipal;

import BACK.Conexao;
import javax.swing.JOptionPane;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;

/**
 *
 * @author johnp
 */
public class Cadastroprodutos extends javax.swing.JFrame {

    /**
     * Creates new form Alterpreco
     */
    public Cadastroprodutos() {
        initComponents();
        setLocationRelativeTo(null);
        setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        ReceberEstoque = new javax.swing.JTextField();
        Divisoria = new javax.swing.JLabel();
        Divisoria1 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        Recebepreconovo = new javax.swing.JTextField();
        Voltar1 = new javax.swing.JButton();
        Confrimarpreco = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        Recebenome = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setBounds(new java.awt.Rectangle(0, 0, 0, 0));
        setFocusCycleRoot(false);
        setMinimumSize(new java.awt.Dimension(552, 498));
        setName("alterapreco"); // NOI18N
        getContentPane().setLayout(null);

        jLabel2.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel2.setText("Estoque:");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(230, 250, 70, 17);

        ReceberEstoque.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ReceberEstoqueActionPerformed(evt);
            }
        });
        getContentPane().add(ReceberEstoque);
        ReceberEstoque.setBounds(200, 270, 120, 30);

        Divisoria.setText("__________________________________________");
        getContentPane().add(Divisoria);
        Divisoria.setBounds(300, 200, 210, 16);

        Divisoria1.setText("_________________________________________");
        getContentPane().add(Divisoria1);
        Divisoria1.setBounds(20, 200, 200, 16);

        jLabel1.setText("R$");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(500, 170, 30, 16);

        jLabel5.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel5.setText("Digite o novo preço:");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(330, 130, 150, 17);

        Recebepreconovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RecebepreconovoActionPerformed(evt);
            }
        });
        getContentPane().add(Recebepreconovo);
        Recebepreconovo.setBounds(300, 160, 200, 30);

        Voltar1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Voltar1.setText("Voltar");
        Voltar1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        Voltar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Voltar1ActionPerformed(evt);
            }
        });
        getContentPane().add(Voltar1);
        Voltar1.setBounds(150, 380, 90, 30);

        Confrimarpreco.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Confrimarpreco.setText("Confirmar");
        Confrimarpreco.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        Confrimarpreco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ConfrimarprecoActionPerformed(evt);
            }
        });
        getContentPane().add(Confrimarpreco);
        Confrimarpreco.setBounds(260, 380, 100, 30);

        jLabel6.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel6.setText("Digite um novo nome:");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(40, 130, 160, 17);

        Recebenome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RecebenomeActionPerformed(evt);
            }
        });
        getContentPane().add(Recebenome);
        Recebenome.setBounds(20, 160, 200, 30);

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/mtpequena.png"))); // NOI18N
        getContentPane().add(jLabel7);
        jLabel7.setBounds(-250, -570, 810, 1070);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void RecebepreconovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RecebepreconovoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RecebepreconovoActionPerformed

    private void Voltar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Voltar1ActionPerformed
        dispose();
    }//GEN-LAST:event_Voltar1ActionPerformed

    private void ConfrimarprecoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ConfrimarprecoActionPerformed
        Conexao conexao = new Conexao();
        String sql = "insert into produtos (nome, preço, estoque) values(?, ?,?);";
        conexao.conectar();
        String nome = Recebenome.getText();
        double preco = Double.parseDouble(Recebepreconovo.getText().replace(',', '.'));
        String estoque = ReceberEstoque.getText();

        try (Connection connection = conexao.getConnection(); PreparedStatement stmt = connection.prepareStatement(sql)) {
            stmt.setString(1, nome);
            stmt.setDouble(2, preco);
            stmt.setString(3, estoque);
            stmt.executeUpdate();
            JOptionPane.showMessageDialog(null, "Produto cadastrado com Sucesso!");
            dispose();
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "Erro ao cadastrar produto: " + e.getMessage(), "Erro", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_ConfrimarprecoActionPerformed

    private void RecebenomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RecebenomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RecebenomeActionPerformed

    private void ReceberEstoqueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ReceberEstoqueActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ReceberEstoqueActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Cadastroprodutos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Cadastroprodutos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Cadastroprodutos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Cadastroprodutos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Cadastroprodutos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Confrimarpreco;
    private javax.swing.JLabel Divisoria;
    private javax.swing.JLabel Divisoria1;
    private javax.swing.JTextField Recebenome;
    private javax.swing.JTextField Recebepreconovo;
    private javax.swing.JTextField ReceberEstoque;
    private javax.swing.JButton Voltar1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    // End of variables declaration//GEN-END:variables
}
