package Telaprincipal;

import BACK.Conexao;
import javax.swing.JOptionPane;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.Date;

/**
 *
 * @author johnp
 */
public class Cadastrofuncionário extends javax.swing.JFrame {

    /**
     * Creates new form Alterpreco
     */
    public Cadastrofuncionário() {
        initComponents();
        setLocationRelativeTo(null);
        setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        ReceberSenha = new javax.swing.JTextField();
        Divisoria = new javax.swing.JLabel();
        Divisoria1 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        RecebeCPF = new javax.swing.JTextField();
        Voltar1 = new javax.swing.JButton();
        Confrimarpreco = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        Recebenome = new javax.swing.JTextField();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jLabel3 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setBounds(new java.awt.Rectangle(0, 0, 0, 0));
        setFocusCycleRoot(false);
        setMinimumSize(new java.awt.Dimension(552, 498));
        setName("alterapreco"); // NOI18N
        getContentPane().setLayout(null);

        jLabel2.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel2.setText("Nascimento:");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(350, 250, 100, 17);

        ReceberSenha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ReceberSenhaActionPerformed(evt);
            }
        });
        getContentPane().add(ReceberSenha);
        ReceberSenha.setBounds(30, 280, 190, 30);

        Divisoria.setText("__________________________________________");
        getContentPane().add(Divisoria);
        Divisoria.setBounds(300, 200, 210, 16);

        Divisoria1.setText("_________________________________________");
        getContentPane().add(Divisoria1);
        Divisoria1.setBounds(20, 200, 200, 16);

        jLabel1.setText("R$");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(500, 170, 30, 16);

        jLabel5.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel5.setText("Digite o CPF");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(330, 130, 150, 17);

        RecebeCPF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RecebeCPFActionPerformed(evt);
            }
        });
        getContentPane().add(RecebeCPF);
        RecebeCPF.setBounds(300, 160, 200, 30);

        Voltar1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Voltar1.setText("Voltar");
        Voltar1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        Voltar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Voltar1ActionPerformed(evt);
            }
        });
        getContentPane().add(Voltar1);
        Voltar1.setBounds(170, 380, 90, 30);

        Confrimarpreco.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Confrimarpreco.setText("Confirmar");
        Confrimarpreco.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        Confrimarpreco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ConfrimarprecoActionPerformed(evt);
            }
        });
        getContentPane().add(Confrimarpreco);
        Confrimarpreco.setBounds(300, 380, 100, 30);

        jLabel6.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel6.setText("Digite um novo nome:");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(40, 130, 160, 17);

        Recebenome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RecebenomeActionPerformed(evt);
            }
        });
        getContentPane().add(Recebenome);
        Recebenome.setBounds(20, 160, 200, 30);

        jDateChooser1.setDateFormatString("y '- M '-' d");
        getContentPane().add(jDateChooser1);
        jDateChooser1.setBounds(310, 280, 180, 30);

        jLabel3.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel3.setText("Digite a senha:");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(80, 250, 120, 17);

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/mtpequena.png"))); // NOI18N
        getContentPane().add(jLabel7);
        jLabel7.setBounds(-250, -570, 810, 1070);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void RecebeCPFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RecebeCPFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RecebeCPFActionPerformed

    private void Voltar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Voltar1ActionPerformed
        dispose();
    }//GEN-LAST:event_Voltar1ActionPerformed

    private void ConfrimarprecoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ConfrimarprecoActionPerformed
        Conexao conexao = new Conexao();
    String sql = "insert into funcionarios (nome, cpf, senha, aniversário) values(?, ?, ?, ?);";
    conexao.conectar();
    String nome = Recebenome.getText();
    String cpf = RecebeCPF.getText();
    String senha = ReceberSenha.getText();
    // Obter a data do componente JDateChooser
    Date dataNascimento = jDateChooser1.getDate();
    
    try (Connection connection = conexao.getConnection(); PreparedStatement stmt = connection.prepareStatement(sql)) {
        stmt.setString(1, nome);
        stmt.setString(2, cpf);
        stmt.setString(3, senha);
        // Formatar a data para o formato do MySQL
        SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
        String dataFormatada = sdf.format(dataNascimento);
        stmt.setString(4, dataFormatada);
        
        stmt.executeUpdate();
        JOptionPane.showMessageDialog(null, "Funcionário cadastrado com Sucesso!");
        dispose();
    } catch (SQLException e) {
        JOptionPane.showMessageDialog(null, "Erro ao cadastrar funcionário: " + e.getMessage(), "Erro", JOptionPane.ERROR_MESSAGE);
    }
    }//GEN-LAST:event_ConfrimarprecoActionPerformed

    private void RecebenomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RecebenomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RecebenomeActionPerformed

    private void ReceberSenhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ReceberSenhaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ReceberSenhaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Cadastrofuncionário.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Cadastrofuncionário.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Cadastrofuncionário.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Cadastrofuncionário.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Cadastrofuncionário().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Confrimarpreco;
    private javax.swing.JLabel Divisoria;
    private javax.swing.JLabel Divisoria1;
    private javax.swing.JTextField RecebeCPF;
    private javax.swing.JTextField Recebenome;
    private javax.swing.JTextField ReceberSenha;
    private javax.swing.JButton Voltar1;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    // End of variables declaration//GEN-END:variables
}
